# Generated by Django 5.1.3 on 2024-11-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='defecive_parts',
            new_name='defective_parts',
        ),
    ]
